"""Typed surface for Hyperbolica's embedded Symbolica extension.

``Expression`` is the one native class created by the Symbolica kernel inside
the Hyperbolica extension.  It is deliberately declared here rather than
aliased to a separately installed ``symbolica`` wheel, whose PyO3 class has a
different runtime identity.
"""

from collections.abc import Sequence
from decimal import Decimal
from typing import Any, ClassVar, overload

__version__: str
__symbolica_version__: str
__api_version__: int
__license__: str
__symbolica_license__: str
__all__: list[str]


class ParseMode:
    Symbolica: ClassVar[ParseMode]
    Mathematica: ClassVar[ParseMode]


class Expression:
    """A native expression owned by Hyperbolica's embedded Symbolica kernel."""

    def __copy__(self) -> Expression: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> Expression: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __neg__(self) -> Expression: ...
    def __add__(self, other: Expression | int | float | complex) -> Expression: ...
    def __radd__(self, other: Expression | int | float | complex) -> Expression: ...
    def __sub__(self, other: Expression | int | float | complex) -> Expression: ...
    def __rsub__(self, other: Expression | int | float | complex) -> Expression: ...
    def __mul__(self, other: Expression | int | float | complex) -> Expression: ...
    def __rmul__(self, other: Expression | int | float | complex) -> Expression: ...
    def __truediv__(self, other: Expression | int | float | complex) -> Expression: ...
    def __rtruediv__(self, other: Expression | int | float | complex) -> Expression: ...
    def __pow__(self, exponent: Expression | int) -> Expression: ...
    def __call__(self, *arguments: Expression | int | float | complex) -> Expression: ...
    def __getattr__(self, name: str) -> Any: ...
    def to_canonical_string(self) -> str: ...


@overload
def S(name: str, /, **attributes: Any) -> Expression: ...
@overload
def S(
    name: str, second_name: str, /, *other_names: str, **attributes: Any
) -> tuple[Expression, ...]: ...


def E(
    expr: str,
    mode: ParseMode = ...,
    default_namespace: str | None = None,
) -> Expression: ...


def N(
    number: int | float | complex | str | Decimal,
    relative_error: float | None = None,
) -> Expression: ...


def get_version() -> str: ...
def is_licensed() -> bool: ...


class HyperbolicaError(Exception):
    """Base class for errors raised by Hyperbolica."""


class InputError(HyperbolicaError):
    """Invalid expression, integration-variable schedule, or options."""


class DuplicateVariableError(InputError):
    variable: str


class AlgebraError(HyperbolicaError):
    """Failure of an exact algebra operation."""


class DivergentIntegralError(HyperbolicaError):
    boundary: str
    variable: str
    log_power: int
    power: int


class UnsupportedFeatureError(HyperbolicaError):
    """The requested integration feature is unavailable for this input."""


class ContextError(AlgebraError):
    variable: str


class IntegrationOptions:
    """Mutable, value-comparable exact integration options."""

    def __init__(
        self,
        *,
        check_divergences: bool = False,
        parallel: bool = True,
        introduce_algebraic_letters: bool = False,
        close_final_positive_letters: bool = True,
        mzv_reductions: Sequence[tuple[str, str]] | None = None,
        mzv_basis: Sequence[str] | None = None,
    ) -> None: ...
    @property
    def check_divergences(self) -> bool: ...
    @check_divergences.setter
    def check_divergences(self, value: bool) -> None: ...
    @property
    def parallel(self) -> bool: ...
    @parallel.setter
    def parallel(self, value: bool) -> None: ...
    @property
    def introduce_algebraic_letters(self) -> bool: ...
    @introduce_algebraic_letters.setter
    def introduce_algebraic_letters(self, value: bool) -> None: ...
    @property
    def close_final_positive_letters(self) -> bool: ...
    @close_final_positive_letters.setter
    def close_final_positive_letters(self, value: bool) -> None: ...
    @property
    def mzv_reductions(self) -> list[tuple[str, str]]: ...
    @mzv_reductions.setter
    def mzv_reductions(self, value: Sequence[tuple[str, str]]) -> None: ...
    @property
    def mzv_basis(self) -> list[str]: ...
    @mzv_basis.setter
    def mzv_basis(self, value: Sequence[str]) -> None: ...
    def __copy__(self) -> IntegrationOptions: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> IntegrationOptions: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...


class PreparedIntegral:
    """Immutable input lowered for repeated integrations."""

    @property
    def integration_variables(self) -> list[Expression]: ...
    @property
    def indeterminates(self) -> list[Expression]: ...
    @property
    def shuffle_term_count(self) -> int: ...
    @property
    def variable_count(self) -> int: ...
    @property
    def indeterminate_count(self) -> int: ...
    @property
    def options(self) -> IntegrationOptions: ...
    def integrate(self, options: IntegrationOptions | None = None) -> Expression: ...
    def integrate_detailed(
        self, options: IntegrationOptions | None = None
    ) -> IntegrationResult: ...
    def __len__(self) -> int: ...
    def __copy__(self) -> PreparedIntegral: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> PreparedIntegral: ...
    def __repr__(self) -> str: ...


class AlgebraicLetter:
    """Immutable metadata for a formal quadratic-root pair."""

    @property
    def index(self) -> int: ...
    @property
    def integration_variable_index(self) -> int: ...
    @property
    def polynomial(self) -> Expression: ...
    @property
    def leading_coefficient(self) -> Expression: ...
    @property
    def root_sum(self) -> Expression: ...
    @property
    def root_product(self) -> Expression: ...
    @property
    def discriminant(self) -> Expression: ...
    @property
    def minus(self) -> Expression: ...
    @property
    def plus(self) -> Expression: ...
    def __copy__(self) -> AlgebraicLetter: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> AlgebraicLetter: ...
    def __repr__(self) -> str: ...


class IntegrationResult:
    """Immutable collected exact result and integration metadata."""

    @property
    def expression(self) -> Expression: ...
    @property
    def integration_variables(self) -> list[Expression]: ...
    @property
    def indeterminates(self) -> list[Expression]: ...
    @property
    def algebraic_letters(self) -> list[AlgebraicLetter]: ...
    @property
    def term_count(self) -> int: ...
    @property
    def algebraic_letter_count(self) -> int: ...
    @property
    def variable_count(self) -> int: ...
    @property
    def indeterminate_count(self) -> int: ...
    @property
    def is_zero(self) -> bool: ...
    def __len__(self) -> int: ...
    def __copy__(self) -> IntegrationResult: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> IntegrationResult: ...
    def __repr__(self) -> str: ...


def prepare(
    expression: Expression,
    variables: Sequence[Expression],
    options: IntegrationOptions | None = None,
) -> PreparedIntegral: ...


def integrate(
    expression: Expression,
    variables: Sequence[Expression],
    options: IntegrationOptions | None = None,
) -> Expression: ...


def integrate_detailed(
    expression: Expression,
    variables: Sequence[Expression],
    options: IntegrationOptions | None = None,
) -> IntegrationResult: ...


def __getattr__(name: str) -> Any: ...
